#!/bin/sh -e

# This script reads $login, which is only set in ROOT/pr.

[ -z "$login" ] &&
	echo "You're not supposed to call ./rets manually. See the README.md." &&
	exit 1

url="http://retsau.torontomls.net:6103/rets-treb3pv/server"
header="rets-version: RETS/1.7"

# Default locations
mkdir -p output headers data

# Default curl arguments
alias req="curl \
	--digest \
	--show-error \
	--cookie-jar data/cookies.txt \
	--cookie data/cookies.txt \
	-u '$login' \
	-H '$header'"

# If you're running a search or a metadata get, check for cookies.txt, meaning
# that you've already logged in.
case "$1" in
	getmetadata|search)
		[ -f data/cookies.txt ] || invalid=1
		[ "$invalid" ] &&
			echo "You have not logged in yet. See the README.md for instructions." &&
			exit 1
		;;
esac

case "$1" in
	login)
		out=output/login.xml
		head=headers/login.txt
		touch $out $head

		req \
			-o $out \
			--dump-header $head \
			"$url/login" ;;

	logout)
		out=output/logout.xml
		head=headers/logout.txt
		touch $out $head

		req \
			-o $out \
			--dump-header $head \
			"$url/logout" ;;

	getmetadata)
		out=output/metadata.xml
		head=headers/metadata.txt
		touch $out $head

		req \
			-o $out \
			--dump-header $head \
			--data Type=METADATA-SYSTEM \
			--data ID=* \
			--data Format=COMPACT \
			"$url/getmetadata" ;;

	serverinformation)
		out=output/serverinformation.xml
		head=headers/serverinformation.txt
		touch $out $head

		req \
			-o $out \
			--dump-header $head \
			"$url/serverinformation" ;;

	search)
		[ -z "$4" ] &&
			echo "Invalid arguments provided. See the README.md for instructions." &&
			exit 1

		search_type=$2
		class=$3
		query=$4

		out=output/search.xml
		head=headers/search.txt
		touch $out $head

		req \
			-o $out \
			--dump-header $head \
	        --data Format=COMPACT \
	        --data SearchType=$search_type \
	        --data Class=$class \
	        --data StandardNames=0 \
	        --data QueryType=DMQL2 \
	        --data Query=$query \
			"$url/search" ;;

	*)
		echo "Invalid usage. See the README.md for instructions."
		exit 1 ;;
esac
